export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_SUCESS = "LOGIN_SUCESS";

export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";
export const REGISTER_USER_SUCESS = "REGISTER_USER_SUCESS";

export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST";
export const LOAD_USER_FAIL = "LOAD_USER_FAIL";
export const LOAD_USER_SUCESS = "LOAD_USER_SUCESS";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
